### ISSUE TITLE
ImportError: cannot import name 'report_pb2'

### ISSUE THREAD

**Issue by michael20at** [tensorflow/adanet#6]
I'm using Winpython 3.6, bazel test -c opt returns no error, I can install the pip package.

But when I try to import adanet I get "ImportError: cannot import name 'report_pb2'"

Full error message is:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Michael\Desktop\WinPython3-6GPU\examples\Sonstiges\adanet\adanet\__init__.py", line 22, in <module>
    from adanet.core import Ensemble
  File "C:\Users\Michael\Desktop\WinPython3-6GPU\examples\Sonstiges\adanet\adanet\core\__init__.py", line 25, in <module>
    from adanet.core.estimator import Estimator
  File "C:\Users\Michael\Desktop\WinPython3-6GPU\examples\Sonstiges\adanet\adanet\core\estimator.py", line 33, in <module>
    from adanet.core.report_accessor import _ReportAccessor
  File "C:\Users\Michael\Desktop\WinPython3-6GPU\examples\Sonstiges\adanet\adanet\core\report_accessor.py", line 24, in <module>
    from adanet.core import report_pb2 as report_proto
ImportError: cannot import name 'report_pb2'

Any idea why?

**Comment by Contractfit** [comment]
I have exactly the same, but on Linux 16.04, python 3.5.2, tensorflow 1.8.0. 

bazel test -c opt returns error: 

> 
//adanet/core:candidate_test                                             FAILED in 0.4s
  /home/jordy/.cache/bazel/_bazel_jordy/2a42af54a45e41dee977742377d30bc8/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/candidate_test/test.log
//adanet/core:ensemble_test                                              FAILED in 0.4s
  /home/jordy/.cache/bazel/_bazel_jordy/2a42af54a45e41dee977742377d30bc8/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/ensemble_test/test.log
//adanet/core:evaluator_test                                             FAILED in 0.5s
  /home/jordy/.cache/bazel/_bazel_jordy/2a42af54a45e41dee977742377d30bc8/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/evaluator_test/test.log
//adanet/core:freezer_test                                               FAILED in 0.5s
  /home/jordy/.cache/bazel/_bazel_jordy/2a42af54a45e41dee977742377d30bc8/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/freezer_test/test.log
//adanet/core:input_utils_test                                           FAILED in 0.4s
  /home/jordy/.cache/bazel/_bazel_jordy/2a42af54a45e41dee977742377d30bc8/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/input_utils_test/test.log
//adanet/core:iteration_test                                             FAILED in 0.4s
  /home/jordy/.cache/bazel/_bazel_jordy/2a42af54a45e41dee977742377d30bc8/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/iteration_test/test.log
//adanet/core:report_accessor_test                                       FAILED in 0.5s
  /home/jordy/.cache/bazel/_bazel_jordy/2a42af54a45e41dee977742377d30bc8/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/report_accessor_test/test.log
//adanet/core:report_materializer_test                                   FAILED in 0.4s
  /home/jordy/.cache/bazel/_bazel_jordy/2a42af54a45e41dee977742377d30bc8/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/report_materializer_test/test.log
//adanet/core:summary_test                                               FAILED in 0.5s
  /home/jordy/.cache/bazel/_bazel_jordy/2a42af54a45e41dee977742377d30bc8/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/summary_test/test.log
//adanet/core:timer_test                                                 FAILED in 0.3s
  /home/jordy/.cache/bazel/_bazel_jordy/2a42af54a45e41dee977742377d30bc8/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/timer_test/test.log
//adanet/core/subnetwork:generator_test                                  FAILED in 0.5s
  /home/jordy/.cache/bazel/_bazel_jordy/2a42af54a45e41dee977742377d30bc8/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/subnetwork/generator_test/test.log
//adanet/core/subnetwork:report_test                                     FAILED in 0.5s
  /home/jordy/.cache/bazel/_bazel_jordy/2a42af54a45e41dee977742377d30bc8/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/core/subnetwork/report_test/test.log
//adanet/examples:simple_dnn_test                                        FAILED in 0.5s
  /home/jordy/.cache/bazel/_bazel_jordy/2a42af54a45e41dee977742377d30bc8/execroot/org_adanet/bazel-out/k8-opt/testlogs/adanet/examples/simple_dnn_test/test.log
//adanet/core:estimator_test                                             FAILED in 20 out of 20 in 0.5s 
INFO: Build completed, 14 tests FAILED, 256 total actions
>

**Comment by michael20at** [comment]
Excuse me, but I think we have a different problem. I already have protobuf 3.6, and bazel works just fine!

I can also do pip install adanet.

The problem arises when I try to import adanet in python, results in "cannot import name 'report_pb2".

Do I have to build my own wheel? There are instructions in folder "pip_package", but I can't seem to build the package as of yet because of linux/windows issues.

Any help appreciated, thanks!

**Comment by michael20at** [comment]
Built my own wheel now, but didn't help, still get  "cannot import name 'report_pb2".

I checked the report_accessor.py file, there is a "from adanet.core import report_pb2 as report_proto" statement, but in the core folder there is no report_pb2 file, so no wonder it doesn't work! 

Am I missunderstanding something here?

**Comment by GitHub30** [comment]
This problem is fixed at db0923f1aaf6cb546ad69da9eb379ea75f83f207

Fix worked when using Python 2

https://colab.research.google.com/github/GitHub30/adanet/blob/google-colaboratory/adanet/examples/tutorials/adanet_objective.colab.ipynb

https://colab.research.google.com/github/GitHub30/adanet/blob/google-colaboratory/adanet/examples/tutorials/customizing_adanet.colab.ipynb

**Comment by cweill** [comment]
This can happen if you built the code from withing your local clone of `adanet`. Try `cd`'ing out of the directory (e.g. `$ cd ~`) and trying again.

**Comment by michael20at** [comment]
First, thanks for the help. I tried it out with Python 2, it works.

But the error still exists on Python 3, even when moving out of the directory. Does Adanet only work with Python 2? If so, I would suggest to update the readme regarding this.

**Comment by cweill** [comment]
AdaNet officially supports Python 2 and Python 3. So if anything doesn't work, it's a bug. :) 

Other users have been able to successfully train their models with both versions. See this [comment](https://github.com/tensorflow/adanet/issues/4#issuecomment-435077964).

**Comment by raijinspecial** [comment]
I had the exact same problem (ImportError: cannot import name 'report_pb2') on Ubuntu 18.04 with python 3.6.6, but I figured out the problem in my case.

I created a virtual environment with pip using conda:
 
conda create --name ada python==3.6 pip

I built and installed the pip package and had no problem importing adanet when running python from the terminal. I got that error when importing into a jupyter notebook, didnt matter what folder I launched it from. 

Problem was that there was an older versions of protobuf (and setuptools) installed by conda alongside the current version installed with pip. Uninstalling the versions from conda-forge fixed the issue. You can use !pip list and !conda list to see where packages came from. I hope this helps.

**Comment by githubgsq** [comment]
I installed through pip. Both python2 and python3 don't work. 
I'm using **protobuf 3.6.1**

Traceback (most recent call last):
  File "./adanet/examples/nasnet_test.py", line 23, in <module>
    from adanet.examples import nasnet
  File "/home/gaosiqi/project/autoML_frameworks/adanet/adanet/__init__.py", line 22, in <module>
    from adanet.core import Ensemble
  File "/home/gaosiqi/project/autoML_frameworks/adanet/adanet/core/__init__.py", line 25, in <module>
    from adanet.core.estimator import Estimator
  File "/home/gaosiqi/project/autoML_frameworks/adanet/adanet/core/estimator.py", line 35, in <module>
    from adanet.core.report_accessor import _ReportAccessor
  File "/home/gaosiqi/project/autoML_frameworks/adanet/adanet/core/report_accessor.py", line 24, in <module>
    from adanet.core import report_pb2 as report_proto
ImportError: cannot import name report_pb2

**Comment by cweill** [comment]
@githubgsq: looks like you are inside a directory like `/home/tf/project/autoML_frameworks/adanet/` that is contains the cloned repo, so Python is looking up local files and failing to find `report_pb2`. Instead, either change to a directory that doesn't include the adanet repo, or delete the repo, and this should be resolved.

**Comment by githubgsq** [comment]
hi, @cweill , I changed to the other dir but same error.
from adanet.core import report_pb2 as report_proto
ImportError: cannot import name report_pb2
It seems that under adanet.core, there's no report_pb2.py
Also, I typed 'python' under $HOME, and
#import report_pb2
![image](https://user-images.githubusercontent.com/23164715/48392855-f8f06b00-e747-11e8-99c6-7cfefeebfabb.png)

**Comment by wuntoguo** [comment]
> hi, @cweill , I changed to the other dir but same error.
> from adanet.core import report_pb2 as report_proto
> ImportError: cannot import name report_pb2
> It seems that under adanet.core, there's no report_pb2.py
> Also, I typed 'python' under $HOME, and
> #import report_pb2
> ![image](https://user-images.githubusercontent.com/23164715/48392855-f8f06b00-e747-11e8-99c6-7cfefeebfabb.png)
> 
> where should I import report_pb2 from please?
> Thanks.

you can use protoc --python_out=./  report.proto create the missing file report_pb2.py

**Comment by cweill** [comment]
This should no longer be an issue when installing from PyPi using `pip install adanet` for AdaNet v0.5.0+

If you are building from `master`, then you will need to first build with Bazel, then copy the generated report_pb2 file to `adanet/core`:

```shell
# Build adanet pip packaging script
bazel build -c opt //... --local_resources 2048,.5,1.0

# Copy generated proto files.
cp bazel-genfiles/adanet/core/report_pb2.py adanet/core
```

In general, if you are looking for the most up to date installation instructions, check out how we install using continuous integration ([.travis.yml currently](https://github.com/tensorflow/adanet/blob/91fdf069ff370e34f55a57398745dd247dafc8a3/.travis.yml)).
